version: "3.8"

services:

  #Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: diy_be_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - diy_backend

  #MySql Service
  mysql:
    image: mysql:8.0.28
    container_name: diy_be_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dockerize/mysql/data:/var/lib/mysql
      - ./dockerize/mysql/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - diy_backend

  #PHP Service
  php:
    image: php:8.0-cli-alpine
    build: 
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    container_name: diy_be_php
    volumes: 
      - .:/var/www/html
    ports: 
      - "9000:9000"
    networks:
      - diy_backend 

  #Composer Service
  composer:
    image: composer:latest
    container_name: diy_be_composer
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks:
      - diy_backend

  #NPM Service
  npm:
    image: node:17
    container_name: diy_be_npm
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  #Artisan Service
  artisan:
    build: 
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    container_name: diy_be_artisan
    volumes: 
      - .:/var/www/html
    depends_on: 
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - diy_backend

#Docker Networks
networks:
  diy_backend: